name: GitHub Action flow to GHCR 

on:
#  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazów na repozytorium
    runs-on: ubuntu-20.04
    env:
      TAG: fibonacci
      REGISTRY: ghcr.io
      TOK: ${{ secrets.GITHUB_TOKEN }}
      USER: Rekaad
      VERSION: v1

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      - name: Log into ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ env.TOK }}

      - name: Log into dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.TAG }}
          tags: type=semver,pattern={{version}},value=${{ env.VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
