name: GitHub Action flow to GHCR 

on:
#  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazów na repozytorium
    runs-on: ubuntu-20.04


    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2